base_images:
  cli:
    name: "4.19"
    namespace: ocp
    tag: cli
  cli-ocm:
    name: cli-ocm
    namespace: ci
    tag: latest
  rosa-aws-cli:
    name: rosa-aws-cli
    namespace: ci
    tag: latest
  upi-installer:
    name: "4.19"
    namespace: ocp
    tag: upi-installer
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.21
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.19"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: quay-e2e-tests-quay-test-env
  cron: 0 12 * * 3
  steps:
    cluster_profile: aws-qe
    env:
      CHANNEL_GROUP: nightly
      OPENSHIFT_VERSION: "4.19"
      QUAY_INDEX_IMAGE_BUILD: brew.registry.redhat.io/rh-osbs/iib-pub-pending:v4.19
      QUAY_OPERATOR_CHANNEL: stable-3.13
      QUAY_OPERATOR_SOURCE: brew-operator-catalog
      QUAY_STORAGE_PROVIDER: awssts
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-resource-provisioning-storage-aws-sts-s3
    - ref: quay-tests-quay-deploy-operator
    - ref: quay-tests-quay-deploy-registry-awssts
    - ref: quay-tests-test-quay-e2e
    - ref: quay-tests-deprovisioning-aws-gcp-azure-storage-buckets
    workflow: rosa-aws-sts
zz_generated_metadata:
  branch: master
  org: quay
  repo: quay-tests
  variant: quay-test-env
