base_images:
  ocp_builder_rhel-8-golang-1.21-openshift-4.18:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.21-openshift-4.18
  tools:
    name: "4.18"
    namespace: ocp
    tag: tools
build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.21-openshift-4.18
releases:
  latest:
    candidate:
      architecture: amd64
      product: ocp
      stream: nightly
      version: "4.18"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: container-security-operator-nightly-test
  cron: 0 12 * * 6
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_NODE_REPLICAS: "8"
      COMPUTE_NODE_TYPE: m6a.8xlarge
      CSO_CHANNEL: stable-3.14
      CSO_SOURCE: cso-catalog
      QUAY_INDEX_IMAGE_BUILD: brew.registry.redhat.io/rh-osbs/iib:947891
      QUAY_OPERATOR_CHANNEL: stable-3.14
      QUAY_OPERATOR_SOURCE: cso-catalog
    test:
    - ref: quay-tests-enable-quay-catalogsource
    - ref: quay-tests-deploy-quay-aws-s3
    - ref: quay-tests-cso-qe-test
    workflow: quay-tests-cucushift-installer-rehearse-aws-ipi-operator
  timeout: 8h0m0s
zz_generated_metadata:
  branch: master
  org: quay
  repo: quay-tests
  variant: container-security-operator
